---
scireum_volumes: &scireum_volumes
  - name: docker_socket
    path: /var/run/docker.sock
  - name: m2
    path: /root/.m2

kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 100

steps:
  - name: validate
    image: scireum/sirius-build-jdk22
    commands:
      - mvn clean validate -U
    volumes: *scireum_volumes

  - name: deploy
    image: scireum/sirius-build-jdk22
    commands:
      - sed -i 's/DEVELOPMENT-SNAPSHOT/${DRONE_TAG}/g' pom.xml
      - mvn clean deploy
    volumes: *scireum_volumes
    when:
      event:
        - tag

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock
  - name: m2
    host:
      path: /root/.m2
